// Mirrors the ContentLayer label/color/bg switches duplicated in
// Feed.razor and FeedDetail.razor — extracted once here per REACT_MIGRATION.md §6.
import type { ContentLayer } from "./types";

const LABELS: Record<ContentLayer, string> = {
  Policy: "Policy",
  Academic: "Research",
  Ideas: "Big Idea",
  Learning: "Learning",
  Video: "Video",
  Skills: "Skills",
  RealEstate: "Real Estate",
  Law: "Law",
  Literature: "Literature",
  Transportation: "Transport",
  Gaming: "Gaming",
  Art: "Art",
  History: "History",
  Sports: "Sports",
  Music: "Music",
  Film: "Film & TV",
  Science: "Science",
  Environment: "Environment",
  Travel: "Travel",
  Medicine: "Medicine",
  Fashion: "Fashion",
  Lifestyle: "Lifestyle",
  Faith: "Faith",
  Philosophy: "Philosophy",
  Education: "Education",
  Finance: "Finance",
  Energy: "Energy",
  Agriculture: "Agriculture",
  Industry: "Industry",
  Career: "Career",
};

const COLORS: Record<ContentLayer, string> = {
  Policy: "#0e5f6b",
  Academic: "#1a4d8f",
  Ideas: "#6b3fa0",
  Learning: "#374151",
  Video: "#374151",
  Skills: "#374151",
  RealEstate: "#b45309",
  Law: "#1e3a5f",
  Literature: "#713f12",
  Transportation: "#44495e",
  Gaming: "#5b21b6",
  Art: "#9d174d",
  History: "#92400e",
  Sports: "#14532d",
  Music: "#831843",
  Film: "#7f1d1d",
  Science: "#0f766e",
  Environment: "#166534",
  Travel: "#0c4a6e",
  Medicine: "#991b1b",
  Fashion: "#7e22ce",
  Lifestyle: "#c2410c",
  Faith: "#78350f",
  Philosophy: "#3b0764",
  Education: "#1e3a8a",
  Finance: "#064e3b",
  Energy: "#78350f",
  Agriculture: "#3f6212",
  Industry: "#374151",
  Career: "#1e3a8a",
};

const BACKGROUNDS: Record<ContentLayer, string> = {
  Policy: "#e0f4f6",
  Academic: "#ddeeff",
  Ideas: "#ede9f7",
  Learning: "#f0f2f4",
  Video: "#f0f2f4",
  Skills: "#f0f2f4",
  RealEstate: "#fef3c7",
  Law: "#e8f0fe",
  Literature: "#fefce8",
  Transportation: "#f0f4f8",
  Gaming: "#ede9fe",
  Art: "#fce7f3",
  History: "#fff7ed",
  Sports: "#dcfce7",
  Music: "#fdf2f8",
  Film: "#fef2f2",
  Science: "#f0fdfa",
  Environment: "#f0fdf4",
  Travel: "#e0f2fe",
  Medicine: "#fee2e2",
  Fashion: "#f3e8ff",
  Lifestyle: "#fff7ed",
  Faith: "#fffbeb",
  Philosophy: "#faf5ff",
  Education: "#eff6ff",
  Finance: "#d1fae5",
  Energy: "#fef3c7",
  Agriculture: "#ecfccb",
  Industry: "#f0f2f4",
  Career: "#dbeafe",
};

export const layerLabel = (layer: ContentLayer): string => LABELS[layer] ?? "Intelligence";
export const layerColor = (layer: ContentLayer): string => COLORS[layer] ?? "#374151";
export const layerBg = (layer: ContentLayer): string => BACKGROUNDS[layer] ?? "#f0f2f4";
